### PR TITLE
Add Windows8 support (scan method only)

### PR DESCRIPTION
**Pull request by vladimir-kotikov**

### CODE REVIEW

**Comment by purplecabbage** [comment]
This has been added to the backlog, and should be merged soon. Thanks.

**Comment by DURK** [comment]
Any updates on this? Is it just me, or is it getting quite complicated to track the progress on a WP8 version of the BarcodeScanner?
- <a href="https://github.com/wildabeast/BarcodeScanner">Wildabeast</a> has 2 unmerged PR's on this issue (<a href="https://github.com/wildabeast/BarcodeScanner/pull/98">1</a>, <a href="https://github.com/wildabeast/BarcodeScanner/pull/64">2</a>)
- <a href="https://github.com/bloxlab/BarcodeScannerWP8">Bloxlab</a> has a plugin dedicated to WP8, but has not been submitted to PG-build.
- <a href="https://github.com/manateeworks/phonegap-mwbarcodescanner">Manateeworks</a> has a plugin for all platforms, but has not been submitted to PG-build.

And then there's this repo, which is forked from Wildabeast's repo and has yet another PR to merge WP8-support.

Being dependent on PG-Build and having to support iOS, Android and WP8, I'm not sure where to look for a solution. Any idea on when this merge could be expected?

Thanks in advance :)

**Comment by vinnylinck** [comment]
This PR covers windows 8 store apps, but I never tested on wp8.
Even this way, I forked the original repo because I could not find a full cross platform solution as well. :(

Looking forward for a unified repo for all this stuff. 

Vinny

**Comment by sgrebnov** [comment]
This PR adds Windows Store Apps support only. We've stared work on similar functionality for Windows Phone and will send separate PR soon.

Please let me know if you are looking for any remaining work here before this PR could be merged? Or we are good to merge this?

**Comment by vinnylinck** [comment]
I think we do better work on WP PR first and then, work on a new PR for W8 store app talking a chance to reuse a good piece of code and make things simpler.

What do you think?

**Comment by sgrebnov** [comment]
Here is implementation for Windows Phone 8. https://github.com/phonegap-build/BarcodeScanner/pull/6 

PS. All core functionality is provided by corresponding  ZXing library. Windows 8 specific plugin wrapper is written on JS and  Windows Phone code is written on C#. I personally don't see a good way to re-use W8/WP8 platform specific plugin code.

**Comment by vinnylinck** [comment]
Thanks. I'm aware about the code differences. Did not look at the code yet, but things can follow a kind of standard instead of having each Platform working differently. ;)

I will take a look on this (and test in my wp8) if you don't mind. Thanks.

**Comment by FabioSSantana** [comment]
Anyone knows when barcodescanner will be enabled in the official version?

Here in Brazil the Windows Phone platform has surpassed the IOS platform, and it keeps gaining market share all over the world as well.

It seems that many contributions has been already developed to be integrated in the final version for WP. It should be prioritysed.

Thanks for any feedback in advance.

**Comment by purplecabbage** [comment]
@wildabeast merge this already!

**Comment by Moadib242** [comment]
Hi all.

This implementation is really very important for any project. Application compatible with all OS is the dream of all developer. 
I'm hoping it becomes available as soon as possible. It also covers the encoder?

Tks in advance.
Tulio

**Comment by vinnylinck** [comment]
The PR I sent is about Windows Store Apps only, not covering Windows Phone
(really important to know).
It doesn't cover the encoder, but I can put that on my back log (or anyone
available can use the current implementation to provide the support).

Best regards
Vinny

**Comment by purplecabbage** [comment]
Note that WP8 is still NOT supported, and also that build.phonegap.com does NOT support windows8 so this is only useful to people who install it via the phonegap-cli or cordova-cli

**Pull request merged**
