### PR TITLE
Changes for 2.7.0 for iOS and Android

### PR DESCRIPTION
**Pull request by dts**
I had to make some minor modifications to the Android code, and had to change the way the config.xml references source files.  If there are better ways to do either, I'm open to it.  I just had to get it working, and this is what I did.

### CODE REVIEW

**Comment by marcelocecin** [comment]
support for CODE_93 and CODE_25 for iOS ?

**Comment by orenagiv** [comment]
Did you deal with the ITF barcode bug on iOS?

**Comment by dts** [comment]
Nope

**Comment by wildabeast** [comment]
wildabeast/BarcodeScanner is the main repo and should be all up to date. PGB and plugins.cordova.io will point there moving forward.

**Pull request closed without merging**
